# Site settings
title: Beginning
description: Limitless.
cover: assets/images/cover.jpg
baseurl: "" # the subpath of your site, e.g. /blog/ or / for root
url: "https://aprilcs0411.github.io/" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

# Social
#facebook: facebook
#twitter: twitter
github:  github

#Additional Pages
about: about
contact: contact
privacy-policy: privacy-policy


permalink: /:title


# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-paginate


# Settings for rake task
safe: False
lsi: False
username: aprilcs0411 #github username
repo: aprilcs0411.github.io #github repository
branch: master #branch
relative_source: ..\aprilcs0411.github.io\ #source directory
destination: ..\aprilcs0411.github.io\ #destination directory
production_url:  https://aprilcs0411.github.io/
source_url:  https://github.com/aprilcs0411/aprilcs0411.github.io #source repository url

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
